/* src/include/config.h.  Generated by configure.  */
/*!NOINDEX*/
/* Define if you have standard C headers. */
#define STDC_HEADERS 1

/* Define if you have "config.h" (yes, you have). */
#define HAVE_CONFIG_H 1

/* Various other header files. */
#define HAVE_GETOPT_H 1
#define HAVE_LIMITS_H 1
#define HAVE_SYS_IPC_H 1
#define HAVE_SYS_PARAM_H 1
#define HAVE_LIBGEN_H 1

/* Functions. */
#define HAVE_GETOPT 1
#define HAVE_GETOPT_LONG 1
#define HAVE_MEMCPY 1
#define HAVE_BASENAME 1
#define HAVE_SNPRINTF 1

/* NLS stuff. */
/* #undef ENABLE_NLS */
#define HAVE_LIBINTL_H 1
#define HAVE_LOCALE_H 1
/* #undef HAVE_GETTEXT */
#ifdef ENABLE_NLS
# include "library/gettext.h"
#else
# define _(String) (String)
# define N_(String) (String)
#endif

/* The name of the program. */
#define PROGRAM_NAME "pv"

/* The name of the package. */
#define PACKAGE "pv"

/* The current package version. */
#define VERSION "1.1.4"

/* Various identification and legal stuff. */
#define COPYRIGHT_YEAR   _("2008")
#define COPYRIGHT_HOLDER _("Andrew Wood <andrew.wood@ivarch.com>")
#define PROJECT_HOMEPAGE "http://www.ivarch.com/programs/" PROGRAM_NAME ".shtml"
#define BUG_REPORTS_TO   _("Andrew Wood <andrew.wood@ivarch.com>")

/* LFS support. */
/* #undef ENABLE_LARGEFILE */
#ifdef ENABLE_LARGEFILE
# define __USE_LARGEFILE64 1
# define _LARGEFILE64_SOURCE 1
#else
# ifndef __APPLE__
#   define stat64 stat
#   define fstat64 fstat
# endif
# define open64 open
# define lseek64 lseek
#endif

/* #undef HAVE_IPC */
#ifdef HAVE_SYS_IPC_H
#define HAVE_IPC 1
#endif

/* EOF */
