/*
 * Automatically generated C config: don't edit
 */
#define AUTOCONF_INCLUDED

/*
 * Core Applications
 */
#define CONFIG_USER_INIT_INIT 1
#undef  CONFIG_USER_INIT_CONSOLE_SH
#undef  CONFIG_USER_INIT_RUN_FIREWALL
#undef  CONFIG_USER_INIT_CONF
#undef  CONFIG_USER_SASH_SH
#undef  CONFIG_USER_SH_SH
#undef  CONFIG_USER_NWSH_SH
#undef  CONFIG_USER_BASH_BASH
#undef  CONFIG_USER_MSH_SH
#define CONFIG_USER_OTHER_SH 1
#undef  CONFIG_USER_SASH_REBOOT
#undef  CONFIG_USER_SASH_REBOOT_SNAPGEAR
#undef  CONFIG_USER_SASH_SHUTDOWN
#undef  CONFIG_USER_INIT_EXPAND
#undef  CONFIG_USER_VERSION_VERSION
#define CONFIG_USER_LOGIN_LOGIN 1
#undef  CONFIG_USER_OLD_PASSWORDS
#undef  CONFIG_USER_ONLY_ROOT
#define CONFIG_USER_AGETTY_AGETTY 1
#undef  CONFIG_USER_GETTYD_GETTYD
#undef  CONFIG_USER_LOGIN_PASSWD
#undef  CONFIG_USER_CRON_CRON

/*
 * Real Time Clock
 */
#undef  CONFIG_USER_HWCLOCK_HWCLOCK
#undef  CONFIG_USER_RTC_M41T11
#undef  CONFIG_USER_RTC_DS1302

/*
 * Vixie-cron
 */
#undef  CONFIG_USER_VIXIECRON_CRON
#undef  CONFIG_USER_VIXIECRON_CRONTAB

/*
 * at
 */
#undef  CONFIG_USER_AT_AT
#undef  CONFIG_USER_AT_ATD
#undef  CONFIG_USER_AT_ATRUN

/*
 * Config scripts
 */
#define CONFIG_USER_REPLIMENU_CFGS 1
#define CONFIG_USER_REPLIMENU 1

/*
 * Library Configuration
 */

/*
 * Force build (Normally built when required)
 */
#undef  CONFIG_LIB_AUDIOFILE_FORCE
#undef  CONFIG_LIB_FLEX_FORCE
#undef  CONFIG_LIB_GPM_FORCE
#undef  CONFIG_LIB_LIBAES_FORCE
#undef  CONFIG_LIB_LIBDES_FORCE
#undef  CONFIG_LIB_LIBSSL_FORCE
#undef  CONFIG_LIB_LIBGMP_FORCE
#undef  CONFIG_LIB_LIBG_FORCE
#undef  CONFIG_LIB_LIBLDAP_FORCE
#undef  CONFIG_LIB_LIBNET_FORCE
#undef  CONFIG_LIB_LIBPAM_FORCE
#undef  CONFIG_LIB_LIBPCAP_FORCE
#undef  CONFIG_LIB_LIBPCRE_FORCE
#undef  CONFIG_LIB_ZLIB_FORCE
#undef  CONFIG_LIB_LIBBZ2_FORCE
#undef  CONFIG_LIB_LIBATM_FORCE
#undef  CONFIG_LIB_LIBPNG_FORCE
#undef  CONFIG_LIB_LIBJPEG_FORCE
#undef  CONFIG_LIB_LIBUPNP_FORCE
#define CONFIG_LIB_NCURSES_FORCE 1
#undef  CONFIG_LIB_STLPORT
#undef  CONFIG_LIB_LIBSAMPLERATE_FORCE
#undef  CONFIG_LIB_STLPORT_SHARED
#undef  CONFIG_LIB_EXPAT_FORCE
#undef  CONFIG_LIB_ADNS_FORCE
#undef  CONFIG_LIB_ARES_FORCE
#undef  CONFIG_LIB_LIBIDN_FORCE
#undef  CONFIG_LIB_LIBCURL_FORCE
#undef  CONFIG_LIB_LIBCRYPT_OLD_FORCE
#undef  CONFIG_LIB_ID3TAG_FORCE
#undef  CONFIG_LIB_MAD_FORCE
#undef  CONFIG_LIB_UCLIBCPP_FORCE
#undef  CONFIG_LIB_LIBWWW_FORCE
#undef  CONFIG_LIB_LIBICONV_FORCE
#undef  CONFIG_LIB_LIBGETTEXT_FORCE
#undef  CONFIG_LIB_LIBGLIB_FORCE
#undef  CONFIG_LIB_TREMOR_FORCE
#undef  CONFIG_LIB_SDL_FORCE
#undef  CONFIG_LIB_SDL_MIXER_FORCE
#undef  CONFIG_LIB_LIBSNDFILE_FORCE

/*
 * Library Configuration
 */
#undef  CONFIG_LIB_UC_LIBC_TIMEZONE

/*
 * Flash Tools
 */
#undef  CONFIG_USER_FLASHW_FLASHW
#undef  CONFIG_USER_NETFLASH_NETFLASH
#undef  CONFIG_USER_RECOVER_STATIC_TFTP
#undef  CONFIG_USER_RECOVER_RECOVER
#undef  CONFIG_USER_SETMAC_SETMAC

/*
 * uCbootloader utils
 */
#undef  CONFIG_USER_BOOTTOOLS_LOADER
#undef  CONFIG_USER_BOOTTOOLS_HIMEMLOADER
#undef  CONFIG_USER_BOOTTOOLS_PRINTBENV
#undef  CONFIG_USER_BOOTTOOLS_SETBENV
#undef  CONFIG_USER_BOOTTOOLS_RESET

/*
 * MTD utils
 */
#undef  CONFIG_USER_MTDUTILS
#undef  CONFIG_USER_MTDUTILS_ERASE
#undef  CONFIG_USER_MTDUTILS_ERASEALL
#undef  CONFIG_USER_MTDUTILS_FTL_CHECK
#undef  CONFIG_USER_MTDUTILS_FTL_FORMAT
#undef  CONFIG_USER_MTDUTILS_MKFSJFFS
#undef  CONFIG_USER_MTDUTILS_MKFSJFFS2
#undef  CONFIG_USER_MTDUTILS_NFTLDUMP
#undef  CONFIG_USER_MTDUTILS_NFTL_FORMAT
#undef  CONFIG_USER_MTDUTILS_NANDDUMP
#undef  CONFIG_USER_MTDUTILS_NANDTEST
#undef  CONFIG_USER_MTDUTILS_NANDWRITE
#undef  CONFIG_USER_MTDUTILS_DOC_LOADBIOS
#undef  CONFIG_USER_MTDUTILS_DOC_LOADIPL

/*
 * Filesystem Applications
 */
#undef  CONFIG_USER_FLATFSD_FLATFSD
#undef  CONFIG_USER_MOUNT_MOUNT
#undef  CONFIG_USER_MOUNT_UMOUNT
#undef  CONFIG_USER_FDISK_FDISK
#undef  CONFIG_USER_FDISK_SFDISK

/*
 * Compression
 */
#define CONFIG_USER_TAR_TAR 1
#define CONFIG_USER_BZIP2_BZIP2 1
#define CONFIG_USER_GZIP_GZIP 1
#define CONFIG_USER_MINIZIP_MINIZIP 1

/*
 * EXT2
 */
#undef  CONFIG_USER_E2FSPROGS_E2FSCK_E2FSCK
#undef  CONFIG_USER_E2FSPROGS_MISC_MKE2FS
#undef  CONFIG_USER_E2FSPROGS_MISC_BADBLOCKS
#undef  CONFIG_USER_E2FSPROGS_MISC_CHATTR
#undef  CONFIG_USER_E2FSPROGS_MISC_DUMPE2FS
#undef  CONFIG_USER_E2FSPROGS_MISC_E2LABEL
#undef  CONFIG_USER_E2FSPROGS_MISC_FSCK
#undef  CONFIG_USER_E2FSPROGS_MISC_LSATTR
#undef  CONFIG_USER_E2FSPROGS_MISC_MKLOST_FOUND
#undef  CONFIG_USER_E2FSPROGS_MISC_TUNE2FS
#undef  CONFIG_USER_E2FSPROGS_MISC_UUIDGEN

/*
 * RESIERFS
 */
#undef  CONFIG_USER_REISERFSPROGS
#undef  CONFIG_USER_REISERFSPROGS_DEBUGRESIERFS
#undef  CONFIG_USER_REISERFSPROGS_MKREISERFS
#undef  CONFIG_USER_REISERFSPROGS_REISERFSCK
#undef  CONFIG_USER_REISERFSPROGS_RESIZE_REISERFS
#undef  CONFIG_USER_REISERFSPROGS_UNPACK

/*
 * SAMBA
 */
#define CONFIG_USER_SAMBA 1
#define CONFIG_USER_SAMBA_SMBD 1
#define CONFIG_USER_SAMBA_NMBD 1
#define CONFIG_USER_SAMBA_SMBMOUNT 1
#define CONFIG_USER_SAMBA_SMBUMOUNT 1

/*
 * SMBFS
 */
#undef  CONFIG_USER_SMBMOUNT_SMBMOUNT
#undef  CONFIG_USER_SMBMOUNT_SMBUMOUNT

/*
 * CRAMFS
 */
#undef  CONFIG_USER_CRAMFS_CRAMFSCK
#undef  CONFIG_USER_CRAMFS_MKCRAMFS

/*
 * MSDOS
 */
#undef  CONFIG_USER_DOSFSTOOLS_MKDOSFS
#define CONFIG_USER_DOSFSTOOLS_DOSFSCK 1

/*
 * COREUTILS
 */
#define CONFIG_USER_COREUTILS_COREUTILS 1
#define CONFIG_USER_MKTEMP 1

/*
 * Network Applications
 */
#undef  CONFIG_USER_APPWEB_APPWEB
#undef  CONFIG_USER_ASTERISK
#undef  CONFIG_USER_FNORD_HTTPD
#define CONFIG_USER_BOA_SRC_BOA 1
#undef  CONFIG_USER_BOA_WITH_SSL
#define CONFIG_USER_BOA_EMERG 1
#define CONFIG_USER_BOA_LOGGING 1
#undef  CONFIG_USER_BITCHX_BITCHX
#undef  CONFIG_USER_BPALOGIN_BPALOGIN
#undef  CONFIG_USER_BR2684CTL_BR2684CTL
#undef  CONFIG_USER_BRCFG_BRCFG
#undef  CONFIG_USER_BRCTL_BRCTL
#define CONFIG_USER_CPSCAN 1
#undef  CONFIG_USER_DHCPCD_DHCPCD
#undef  CONFIG_USER_DHCPCD_NEW_DHCPCD
#undef  CONFIG_USER_DHCPD_DHCPD
#undef  CONFIG_USER_DHCP_ISC_SERVER_DHCPD
#undef  CONFIG_USER_DHCP_ISC_CLIENT_DHCLIENT
#undef  CONFIG_USER_DHCP_ISC_RELAY_DHCRELAY
#undef  CONFIG_USER_DIALD_DIALD
#undef  CONFIG_USER_DISCARD_DISCARD
#define CONFIG_USER_INADYN_INADYN 1
#undef  CONFIG_USER_DISCARD_INETD_ECHO
#undef  CONFIG_USER_DNSMASQ_DNSMASQ
#define CONFIG_USER_DROPBEAR_DROPBEAR 1
#undef  CONFIG_USER_ETHATTACH_ETHATTACH
#undef  CONFIG_USER_ETHTOOL_ETHTOOL
#undef  CONFIG_USER_EZIPUPDATE_EZIPUPDATE
#undef  CONFIG_USER_FAKEIDENTD_IDENTD
#undef  CONFIG_USER_DDNS3_CLIENT_DDNS3
#undef  CONFIG_USER_FTP_FTP_FTP
#define CONFIG_USER_FTPD_FTPD 1
#undef  CONFIG_USER_FREESWAN
#undef  CONFIG_USER_OPENSWAN
#undef  CONFIG_USER_HTTPD_HTTPD
#undef  CONFIG_USER_HTTPTUNNEL_CLIENT
#undef  CONFIG_USER_HTTPTUNNEL_SERVER
#undef  CONFIG_USER_IFATTACH_IFATTACH
#define CONFIG_USER_INETD_INETD 1
#undef  CONFIG_USER_IPCHAINS_IPCHAINS
#undef  CONFIG_USER_IPFWADM_IPFWADM
#undef  CONFIG_USER_IPMASQADM_IPMASQADM
#undef  CONFIG_USER_IPPORTFW_IPPORTFW
#undef  CONFIG_USER_IPREDIR_IPREDIR
#undef  CONFIG_USER_IPROUTE2
#undef  CONFIG_USER_IPSENTINEL_IPSENTINEL
#define CONFIG_USER_IPTABLES_IPTABLES 1
#undef  CONFIG_USER_IPTABLES_IP6TABLES
#undef  CONFIG_USER_IPUTILS_IPUTILS
#define CONFIG_USER_IRSSI_IRSSI 1
#define CONFIG_LIB_LIBICONV 1
#define CONFIG_LIB_LIBGETTEXT 1
#define CONFIG_LIB_LIBGLIB 1
#undef  CONFIG_USER_KENDIN_CONFIG
#undef  CONFIG_USER_KLAXON_KLAXON
#undef  CONFIG_USER_L2TPD_L2TPD
#define CONFIG_USER_LINKS_LINKS 1
#define CONFIG_LIB_LIBSSL 1
#define CONFIG_USER_LINKS_WITH_GPM 1
#define CONFIG_LIB_GPM 1
#define CONFIG_USER_LINKS_WITH_GRAPHICS 1
#define CONFIG_LIB_LIBPNG 1
#define CONFIG_LIB_LIBJPEG 1
#undef  CONFIG_USER_LINUXIGD_LINUXIGD
#undef  CONFIG_USER_LOATTACH_LOATTACH
#undef  CONFIG_USER_LRPSTAT_LRPSTAT
#undef  CONFIG_USER_SMTP_SMTPCLIENT
#undef  CONFIG_USER_MAIL_MAIL_IP
#undef  CONFIG_USER_MINI_HTTPD_MINI_HTTPD
#undef  CONFIG_USER_MSNTP_MSNTP
#define CONFIG_USER_NAIL 1
#undef  CONFIG_USER_NESSUS_NASL
#define CONFIG_USER_NCFTP_NCFTP 1
#define CONFIG_USER_NETCAT_NETCAT 1
#undef  CONFIG_USER_NETSTAT_NAT_NETSTAT_NAT
#define CONFIG_USER_NGREP 1
#define CONFIG_LIB_LIBPCAP 1
#define CONFIG_USER_NTPCLIENT_NTPCLIENT 1
#undef  CONFIG_USER_NTPCLIENT_ADJTIMEX
#undef  CONFIG_USER_NTPD_NTPD
#undef  CONFIG_USER_NTPD_NTPDATE
#undef  CONFIG_USER_NTPD_NTPQ
#undef  CONFIG_USER_OPENSSL_APPS
#define CONFIG_USER_OPENVPN 1
#define CONFIG_USER_PING_PING 1
#undef  CONFIG_USER_PLUG_PLUG
#undef  CONFIG_USER_POP3PROXY_POP3PROXY
#undef  CONFIG_USER_PORTMAP_PORTMAP
#undef  CONFIG_USER_PPPD_PPPD_PPPD
#undef  CONFIG_USER_PPTPD_PPTPCTRL
#undef  CONFIG_USER_PPTPD_PPTPD
#undef  CONFIG_USER_PPTP_CLIENT_PPTP
#undef  CONFIG_USER_PPTP_CLIENT_PPTP_CALLMGR
#undef  CONFIG_USER_PROFTPD_PROFTPD
#undef  CONFIG_USER_RADVD_RADVD
#undef  CONFIG_USER_RDATE_RDATE
#define CONFIG_USER_RETAWQ_RETAWQ 1
#undef  CONFIG_USER_ROUTED_ROUTED
#undef  CONFIG_USER_RP_PPPOE_PPPOE
#undef  CONFIG_USER_RP_PPPOE_PPPOE_SERVER
#undef  CONFIG_USER_RSYSLOGD_RSYSLOGD
#undef  CONFIG_USER_SER_SER
#undef  CONFIG_USER_SETHDLC_SETHDLC
#undef  CONFIG_USER_SLATTACH_SLATTACH
#undef  CONFIG_USER_SMTP_SMTPFILTER
#undef  CONFIG_USER_SNMPD_SNMPD
#undef  CONFIG_USER_SNORT_SNORT
#undef  CONFIG_USER_SPEEDTOUCH_MODEM_RUN
#undef  CONFIG_USER_STUNNEL_STUNNEL
#undef  CONFIG_USER_SSLWRAP_SSLWRAP
#undef  CONFIG_USER_SQUID_SQUID
#undef  CONFIG_USER_SSH_SSH
#undef  CONFIG_USER_SSH_SSHD
#undef  CONFIG_USER_SSH_SSHKEYGEN
#undef  CONFIG_USER_STP_STP
#undef  CONFIG_USER_TCPWRAP_TCPD
#undef  CONFIG_USER_TCPBLAST_TCPBLAST
#define CONFIG_USER_TCPDUMP_TCPDUMP 1
#define CONFIG_LIB_LIBPCAP 1
#undef  CONFIG_USER_TELNETD_TELNETD
#define CONFIG_USER_TELNET_TELNET 1
#define CONFIG_LIB_LIBG 1
#undef  CONFIG_USER_TFTP_TFTP
#undef  CONFIG_USER_TFTPD_TFTPD
#undef  CONFIG_USER_THTTPD_THTTPD
#define CONFIG_USER_TINYIRC_TINYIRC 1
#define CONFIG_USER_TINTIN_TINTIN 1
#define CONFIG_USER_TMSNC 1
#define CONFIG_USER_TRACEROUTE_TRACEROUTE 1
#undef  CONFIG_USER_VCONFIG_VCONFIG
#undef  CONFIG_USER_VPNLED_VPNLED
#define CONFIG_USER_WGET 1
#define CONFIG_USER_WNC_WNC 1
#define CONFIG_USER_DIALOG_DIALOG 1
#define CONFIG_USER_BUSYBOX_EXPR 1
#undef  CONFIG_USER_ZEBRA_ZEBRA_ZEBRA

/*
 * Net-tools
 */
#define CONFIG_USER_NET_TOOLS_ARP 1
#undef  CONFIG_USER_NET_TOOLS_HOSTNAME
#undef  CONFIG_USER_NET_TOOLS_IFCONFIG
#undef  CONFIG_USER_NET_TOOLS_NAMEIF
#define CONFIG_USER_NET_TOOLS_NETSTAT 1
#undef  CONFIG_USER_NET_TOOLS_PLIPCONFIG
#undef  CONFIG_USER_NET_TOOLS_RARP
#define CONFIG_USER_NET_TOOLS_ROUTE 1
#undef  CONFIG_USER_NET_TOOLS_SLATTACH
#undef  CONFIG_USER_NET_TOOLS_MII_TOOL
#undef  CONFIG_USER_NET_TOOLS_MII_TOOL_FEC

/*
 * Wireless-tools
 */
#define CONFIG_USER_WIRELESS_TOOLS 1
#define CONFIG_USER_WIRELESS_TOOLS_IWCONFIG 1
#undef  CONFIG_USER_WIRELESS_TOOLS_IWGETID
#define CONFIG_USER_WIRELESS_TOOLS_IWLIST 1
#undef  CONFIG_USER_WIRELESS_TOOLS_IWPRIV
#undef  CONFIG_USER_WIRELESS_TOOLS_IWSPY
#undef  CONFIG_USER_HOSTAP_HOSTAP
#undef  CONFIG_USER_WLAN_NG

/*
 * net-snmp
 */
#undef  CONFIG_USER_UCDSNMP_SNMPD

/*
 * Miscellaneous Applications
 */
#undef  CONFIG_USER_LANG_A60
#undef  CONFIG_USER_ARJ_ARJ
#define CONFIG_USER_AUTOLOGIN_AUTOLOGIN 1
#define CONFIG_USER_BZIP2_BZIP2 1
#define CONFIG_LIB_LIBBZ2 1
#define CONFIG_USER_BC_BC 1
#define CONFIG_USER_CAL_CAL 1
#undef  CONFIG_USER_CHAT_CHAT
#undef  CONFIG_USER_CKSUM_CKSUM
#undef  CONFIG_USER_CLAMAV_CLAMAV
#undef  CONFIG_USER_CLOCK_CLOCK
#define CONFIG_USER_CMATRIX_CMATRIX 1
#define CONFIG_USER_DIFFUTILS_CMP 1
#define CONFIG_USER_CONSOLETOOLS_CONSOLETOOLS 1
#define CONFIG_USER_CONSOLETOOLS_FONTFILETOOLS 1
#define CONFIG_USER_CONSOLETOOLS_SCREENFONTTOOLS 1
#define CONFIG_USER_CONSOLETOOLS_VTTOOLS 1
#define CONFIG_USER_CPU_CPU 1
#undef  CONFIG_USER_CRYPTO_TOOLS_CRYPTOTEST
#undef  CONFIG_USER_CRYPTO_TOOLS_CRYPTOKEYTEST
#undef  CONFIG_USER_CAL_DATE
#define CONFIG_USER_DC_DC 1
#undef  CONFIG_USER_DHRYSTONE_DHRYSTONE
#define CONFIG_USER_DIALOG_DIALOG 1
#define CONFIG_USER_DICTIONARY 1
#undef  CONFIG_USER_DICTIONARY_AMERICAN
#define CONFIG_USER_DICTIONARY_BRITISH 1
#define CONFIG_USER_DIFFUTILS_DIFF 1
#undef  CONFIG_USER_DE2TSCAL_DE2TSCAL
#define CONFIG_USER_DLDITOOL_DLDITOOL 1
#undef  CONFIG_USER_EXPAT_EXAMPLES
#define CONFIG_USER_FBVIEW 1
#define CONFIG_LIB_PNG 1
#define CONFIG_LIB_ZLIB 1
#undef  CONFIG_USER_FROB_LED_FROB_LED
#define CONFIG_USER_FROTZ_FROTZ 1
#undef  CONFIG_USER_GDB_GDBREPLAY
#define CONFIG_USER_GDB_GDBSERVER 1
#undef  CONFIG_USER_GDBSERVER_GDBREPLAY
#undef  CONFIG_USER_GDBSERVER_GDBSERVER
#undef  CONFIG_USER_GREP_GREP
#undef  CONFIG_USER_HD_HD
#define CONFIG_USER_HEXEDIT_HEXEDIT 1
#define CONFIG_USER_HINGED_HINGED 1
#define CONFIG_USER_HINGED_EXAMPLE 1
#define CONFIG_USER_HNB 1
#define CONFIG_USER_IMAGEMAGICK 1
#define CONFIG_USER_LCALC_LCALC 1
#undef  CONFIG_USER_LCD_LCD
#undef  CONFIG_USER_LEDCON_LEDCON
#define CONFIG_USER_LESS_LESS 1
#undef  CONFIG_USER_LHA_LHA
#undef  CONFIG_USER_LILO_LILO
#define CONFIG_USER_LISSA_LISSA 1
#undef  CONFIG_USER_LPR
#undef  CONFIG_USER_USBCBI_USBCBI
#undef  CONFIG_USER_USBISO_USBISO
#define CONFIG_USER_MANPAGES 1
#undef  CONFIG_USER_MATH_TEST
#define CONFIG_USER_MATHOMATIC 1
#undef  CONFIG_USER_MAWK_AWK
#define CONFIG_USER_MC 1
#define CONFIG_USER_MPC 1
#define CONFIG_USER_NCMPC 1
#undef  CONFIG_USER_MYSQL
#undef  CONFIG_USER_NULL_NULL
#undef  CONFIG_USER_PALMBOT_PALMBOT
#undef  CONFIG_USER_PCMCIA_CS
#define CONFIG_USER_PERL_PERL 1
#define CONFIG_USER_PICOC_PICOC 1
#define CONFIG_USER_PV 1
#undef  CONFIG_USER_PYTHON_PYTHON
#undef  CONFIG_USER_READPROFILE_READPROFILE
#define CONFIG_USER_REPLIMENU 1
#undef  CONFIG_USER_ROOTLOADER_ROOTLOADER
#undef  CONFIG_USER_RL_RL
#define CONFIG_USER_SC 1
#define CONFIG_USER_SED_SED 1
#undef  CONFIG_USER_SETSERIAL_SETSERIAL
#define CONFIG_USER_SNAPSHOT 1
#define CONFIG_LIB_LIBPNG 1
#define CONFIG_LIB_ZLIB 1
#define CONFIG_USER_SQLITE 1
#undef  CONFIG_USER_TRIPWIRE_SIGGEN
#define CONFIG_USER_SL_SL 1
#undef  CONFIG_USER_STRACE_STRACE
#undef  CONFIG_USER_STTY_STTY
#undef  CONFIG_USER_TCSH_TCSH
#undef  CONFIG_USER_TINYTCL_TCLSH
#undef  CONFIG_USER_THREADDEMOS_THREADDEMOS
#undef  CONFIG_USER_TIP_TIP
#undef  CONFIG_USER_TRIPWIRE_TRIPWIRE
#define CONFIG_USER_TINYSID_TINYSID 1
#undef  CONFIG_USER_UNRAR_UNRAR
#define CONFIG_USER_UNZIP_UNZIP 1
#define CONFIG_USER_UNZIP_FUNZIP 1
#undef  CONFIG_USER_UNZOO_UNZOO
#define CONFIG_USER_WARP 1
#define CONFIG_LIB_SDL 1
#undef  CONFIG_USER_LRZSZ_LRZSZ

/*
 * LIRC
 */
#undef  CONFIG_USER_LIRC
#undef  CONFIG_USER_LIRC_LIRCD
#undef  CONFIG_USER_LIRC_IRRECORD
#undef  CONFIG_USER_LIRC_LIRCMD
#undef  CONFIG_USER_LIRC_IREXEC
#undef  CONFIG_USER_LIRC_IRW
#undef  CONFIG_USER_LIRC_MODE2

/*
 * QSPI
 */
#undef  CONFIG_MCF_QSPI
#undef  CONFIG_USER_QSPITEST_TEST
#undef  CONFIG_USER_QSPITEST_RX

/*
 * Editors
 */
#define CONFIG_USER_NANO 1
#undef  CONFIG_USER_LEVEE_VI
#undef  CONFIG_USER_ELVISTINY_VI
#undef  CONFIG_USER_JOE

/*
 * Audio tools
 */
#define CONFIG_USER_MADPLAY 1
#define CONFIG_LIB_ZLIB 1
#define CONFIG_LIB_ID3TAG 1
#define CONFIG_LIB_MAD 1
#define CONFIG_USER_MP3PLAY_MP3PLAY 1
#undef  CONFIG_USER_MP3PLAY_SWAP_WD
#define CONFIG_USER_ESD 1
#define CONFIG_LIB_AUDIOFILE 1
#undef  CONFIG_USER_OGGPLAY_OGG123
#define CONFIG_USER_OGGPLAY_EXAMPLE 1
#undef  CONFIG_USER_MUSICBOX_MUSICBOX
#undef  CONFIG_USER_PLAY_PLAY
#undef  CONFIG_USER_PLAY_TONE
#define CONFIG_USER_VPLAY_VPLAY 1
#define CONFIG_USER_VPLAY_VREC 1
#undef  CONFIG_USER_VPLAY_MIXER
#undef  CONFIG_USER_PLAYRT_PLAYRT
#define CONFIG_USER_PLAYTZX_PLAYTZX 1
#define CONFIG_USER_RAWREC_RAWREC 1
#define CONFIG_USER_RAWREC_RAWPLAY 1
#undef  CONFIG_USER_SOX
#define CONFIG_USER_XMP_XMP 1

/*
 * Video tools
 */
#undef  CONFIG_USER_CAMSERV
#undef  CONFIG_USER_W3CAM_VIDCAT
#undef  CONFIG_USER_W3CAM_W3CAMD

/*
 * Fileutils tools
 */
#define CONFIG_USER_FILEUTILS_CAT 1
#undef  CONFIG_USER_FILEUTILS_CHGRP
#undef  CONFIG_USER_FILEUTILS_CHMOD
#undef  CONFIG_USER_FILEUTILS_CHOWN
#define CONFIG_USER_FILEUTILS_CMP 1
#define CONFIG_USER_FILEUTILS_CP 1
#define CONFIG_USER_FILEUTILS_DD 1
#undef  CONFIG_USER_FILEUTILS_GREP
#undef  CONFIG_USER_FILEUTILS_L
#define CONFIG_USER_FILEUTILS_LN 1
#undef  CONFIG_USER_FILEUTILS_LS
#define CONFIG_USER_FILEUTILS_MKDIR 1
#undef  CONFIG_USER_FILEUTILS_MKFIFO
#undef  CONFIG_USER_FILEUTILS_MKNOD
#define CONFIG_USER_FILEUTILS_MORE 1
#define CONFIG_USER_FILEUTILS_MV 1
#define CONFIG_USER_FILEUTILS_RM 1
#define CONFIG_USER_FILEUTILS_RMDIR 1
#define CONFIG_USER_FILEUTILS_SYNC 1
#define CONFIG_USER_FILEUTILS_TOUCH 1

/*
 * Shutils tools
 */
#define CONFIG_USER_SHUTILS_BASENAME 1
#define CONFIG_USER_SHUTILS_DATE 1
#define CONFIG_USER_SHUTILS_DIRNAME 1
#undef  CONFIG_USER_SHUTILS_ECHO
#define CONFIG_USER_SHUTILS_FALSE 1
#undef  CONFIG_USER_SHUTILS_LOGNAME
#undef  CONFIG_USER_SHUTILS_PRINTENV
#define CONFIG_USER_SHUTILS_PWD 1
#undef  CONFIG_USER_SHUTILS_TRUE
#undef  CONFIG_USER_SHUTILS_UNAME
#undef  CONFIG_USER_SHUTILS_WHICH
#undef  CONFIG_USER_SHUTILS_WHOAMI
#undef  CONFIG_USER_SHUTILS_YES

/*
 * Sysutils tools
 */
#undef  CONFIG_USER_SYSUTILS_REBOOT
#undef  CONFIG_USER_SYSUTILS_SHUTDOWN
#undef  CONFIG_USER_SYSUTILS_DF
#define CONFIG_USER_SYSUTILS_FREE 1
#undef  CONFIG_USER_SYSUTILS_HOSTNAME
#undef  CONFIG_USER_SYSUTILS_KILL
#define CONFIG_USER_SYSUTILS_PS 1

/*
 * Procps tools
 */
#undef  CONFIG_USER_PROCPS_FREE
#undef  CONFIG_USER_PROCPS_KILL
#undef  CONFIG_USER_PROCPS_PGREP
#undef  CONFIG_USER_PROCPS_PKILL
#undef  CONFIG_USER_PROCPS_PS
#undef  CONFIG_USER_PROCPS_SNICE
#undef  CONFIG_USER_PROCPS_SYSCTL
#undef  CONFIG_USER_PROCPS_TLOAD
#undef  CONFIG_USER_PROCPS_TOP
#undef  CONFIG_USER_PROCPS_UPTIME
#undef  CONFIG_USER_PROCPS_VMSTAT
#undef  CONFIG_USER_PROCPS_W
#undef  CONFIG_USER_PROCPS_WATCH

/*
 * PCI utilities
 */
#undef  CONFIG_USER_PCIUTILS_LSPCI
#undef  CONFIG_USER_PCIUTILS_SETPCI

/*
 * PIXIL PDA GUI
 */
#define CONFIG_USER_PIXIL 1
#define CONFIG_LIB_UCLIBCPP 1
#define CONFIG_LIB_LIBWWW 1

/*
 * 
 */
#undef  CONFIG_USER_CXXTEST_CXXTEST

/*
 * BusyBox
 */
#define CONFIG_USER_BUSYBOX_BUSYBOX 1

/*
 * Applets
 */
#undef  CONFIG_USER_BUSYBOX_ADDGROUP
#undef  CONFIG_USER_BUSYBOX_ADDUSER
#undef  CONFIG_USER_BUSYBOX_ADJTIMEX
#undef  CONFIG_USER_BUSYBOX_AR
#undef  CONFIG_USER_BUSYBOX_ARPING
#undef  CONFIG_USER_BUSYBOX_AWK
#undef  CONFIG_USER_BUSYBOX_BASENAME
#undef  CONFIG_USER_BUSYBOX_BUNZIP2
#undef  CONFIG_USER_BUSYBOX_CAL
#undef  CONFIG_USER_BUSYBOX_CAT
#define CONFIG_USER_BUSYBOX_CHGRP 1
#define CONFIG_USER_BUSYBOX_CHMOD 1
#define CONFIG_USER_BUSYBOX_CHOWN 1
#undef  CONFIG_USER_BUSYBOX_CHROOT
#undef  CONFIG_USER_BUSYBOX_CHVT
#define CONFIG_USER_BUSYBOX_CLEAR 1
#undef  CONFIG_USER_BUSYBOX_CMP
#undef  CONFIG_USER_BUSYBOX_CP
#undef  CONFIG_USER_BUSYBOX_CPIO
#undef  CONFIG_USER_BUSYBOX_CROND
#undef  CONFIG_USER_BUSYBOX_CRONTAB
#undef  CONFIG_USER_BUSYBOX_CUT
#undef  CONFIG_USER_BUSYBOX_DATE
#undef  CONFIG_USER_BUSYBOX_DC
#undef  CONFIG_USER_BUSYBOX_DD
#undef  CONFIG_USER_BUSYBOX_DEALLOCVT
#define CONFIG_USER_BUSYBOX_DELGROUP 1
#define CONFIG_USER_BUSYBOX_DELUSER 1
#undef  CONFIG_USER_BUSYBOX_DEVFSD
#define CONFIG_USER_BUSYBOX_DF 1
#undef  CONFIG_USER_BUSYBOX_DIRNAME
#define CONFIG_USER_BUSYBOX_DMESG 1
#define CONFIG_USER_BUSYBOX_DOS2UNIX 1
#undef  CONFIG_USER_BUSYBOX_DPKG
#undef  CONFIG_USER_BUSYBOX_DPKG_DEB
#undef  CONFIG_USER_BUSYBOX_DUTMP
#define CONFIG_USER_BUSYBOX_DU 1
#define CONFIG_USER_BUSYBOX_DU_DEFALT_BLOCKSIZE_1K 1
#undef  CONFIG_USER_BUSYBOX_DUMPKMAP
#define CONFIG_USER_BUSYBOX_ECHO 1
#undef  CONFIG_USER_BUSYBOX_FANCY_ECHO
#define CONFIG_USER_BUSYBOX_ENV 1
#define CONFIG_USER_BUSYBOX_EXPR 1
#define CONFIG_USER_BUSYBOX_FBSET 1
#define CONFIG_USER_BUSYBOX_FBSET_FANCY 1
#undef  CONFIG_USER_BUSYBOX_FBSET_READMODE
#undef  CONFIG_USER_BUSYBOX_FDFLUSH
#undef  CONFIG_USER_BUSYBOX_FDFORMAT
#undef  CONFIG_USER_BUSYBOX_FDISK
#define CONFIG_USER_BUSYBOX_FIND 1
#undef  CONFIG_USER_BUSYBOX_FIND_TYPE
#undef  CONFIG_USER_BUSYBOX_FIND_PERM
#undef  CONFIG_USER_BUSYBOX_FIND_MTIME
#undef  CONFIG_USER_BUSYBOX_FIND_NEWER
#undef  CONFIG_USER_BUSYBOX_FIND_INUM
#undef  CONFIG_USER_BUSYBOX_FIND_XDEV
#undef  CONFIG_USER_BUSYBOX_FOLD
#undef  CONFIG_USER_BUSYBOX_FREE
#undef  CONFIG_USER_BUSYBOX_FREERAMDISK
#undef  CONFIG_USER_BUSYBOX_FSCK_MINIX
#undef  CONFIG_USER_BUSYBOX_FTPGET
#undef  CONFIG_USER_BUSYBOX_FTPPUT
#undef  CONFIG_USER_BUSYBOX_GETOPT
#undef  CONFIG_USER_BUSYBOX_GETTY
#define CONFIG_USER_BUSYBOX_GREP 1
#define CONFIG_USER_BUSYBOX_GREP_CONTEXT 1
#define CONFIG_USER_BUSYBOX_GREP_EGREP_ALIAS 1
#define CONFIG_USER_BUSYBOX_GREP_FGREP_ALIAS 1
#undef  CONFIG_USER_BUSYBOX_GUNZIP
#undef  CONFIG_USER_BUSYBOX_GZIP
#undef  CONFIG_USER_BUSYBOX_HALT
#undef  CONFIG_USER_BUSYBOX_HDPARM
#undef  CONFIG_USER_BUSYBOX_HEAD
#undef  CONFIG_USER_BUSYBOX_HEXDUMP
#undef  CONFIG_USER_BUSYBOX_HOSTID
#define CONFIG_USER_BUSYBOX_HOSTNAME 1
#undef  CONFIG_USER_BUSYBOX_HTTPD
#undef  CONFIG_USER_BUSYBOX_HWCLOCK
#define CONFIG_USER_BUSYBOX_ID 1
#define CONFIG_USER_BUSYBOX_IFCONFIG 1
#define CONFIG_USER_BUSYBOX_IFCONFIG_STATUS 1
#undef  CONFIG_USER_BUSYBOX_IFCONFIG_SLIP
#undef  CONFIG_USER_BUSYBOX_IFCONFIG_HW
#undef  CONFIG_USER_BUSYBOX_IFCONFIG_MEMSTART_IOADDR_IRQ
#undef  CONFIG_USER_BUSYBOX_IFCONFIG_BROADCAST_PLUS
#undef  CONFIG_USER_BUSYBOX_IFUPDOWN
#undef  CONFIG_USER_BUSYBOX_INETD
#undef  CONFIG_USER_BUSYBOX_INIT
#undef  CONFIG_USER_BUSYBOX_INSMOD
#undef  CONFIG_USER_BUSYBOX_LSMOD
#undef  CONFIG_USER_BUSYBOX_MODPROBE
#undef  CONFIG_USER_BUSYBOX_RMMOD
#undef  CONFIG_USER_BUSYBOX_2_2_MODULES
#undef  CONFIG_USER_BUSYBOX_2_4_MODULES
#undef  CONFIG_USER_BUSYBOX_2_6_MODULES
#undef  CONFIG_USER_BUSYBOX_INSMOD_VERSION_CHECKING
#undef  CONFIG_USER_BUSYBOX_IPADDR
#define CONFIG_USER_BUSYBOX_IPCALC 1
#define CONFIG_USER_BUSYBOX_IPCALC_FANCY 1
#undef  CONFIG_USER_BUSYBOX_IPLINK
#undef  CONFIG_USER_BUSYBOX_IPROUTE
#undef  CONFIG_USER_BUSYBOX_IPTUNNEL
#define CONFIG_USER_BUSYBOX_KILL 1
#define CONFIG_USER_BUSYBOX_KILLALL 1
#undef  CONFIG_USER_BUSYBOX_KLOGD
#undef  CONFIG_USER_BUSYBOX_LENGTH
#undef  CONFIG_USER_BUSYBOX_LAST
#undef  CONFIG_USER_BUSYBOX_LN
#undef  CONFIG_USER_BUSYBOX_LOADACM
#undef  CONFIG_USER_BUSYBOX_LOADFONT
#undef  CONFIG_USER_BUSYBOX_LOADKMAP
#undef  CONFIG_USER_BUSYBOX_LOGGER
#undef  CONFIG_USER_BUSYBOX_LOGIN
#undef  CONFIG_USER_BUSYBOX_LOGNAME
#undef  CONFIG_USER_BUSYBOX_LOGREAD
#undef  CONFIG_USER_BUSYBOX_LOSETUP
#define CONFIG_USER_BUSYBOX_LS 1
#undef  CONFIG_USER_BUSYBOX_LS_USERNAME
#undef  CONFIG_USER_BUSYBOX_LS_TIMESTAMPS
#undef  CONFIG_USER_BUSYBOX_LS_FILETYPES
#define CONFIG_USER_BUSYBOX_LS_SORTFILES 1
#undef  CONFIG_USER_BUSYBOX_LS_RECURSIVE
#undef  CONFIG_USER_BUSYBOX_LS_FOLLOWLINKS
#define CONFIG_USER_BUSYBOX_LS_COLOR 1
#undef  CONFIG_USER_BUSYBOX_MAKEDEVS
#undef  CONFIG_USER_BUSYBOX_MD5SUM
#undef  CONFIG_USER_BUSYBOX_MESG
#undef  CONFIG_USER_BUSYBOX_MKDIR
#undef  CONFIG_USER_BUSYBOX_MKFIFO
#undef  CONFIG_USER_BUSYBOX_MKFS_MINIX
#define CONFIG_USER_BUSYBOX_MKNOD 1
#undef  CONFIG_USER_BUSYBOX_MKSWAP
#undef  CONFIG_USER_BUSYBOX_MKTEMP
#undef  CONFIG_USER_BUSYBOX_MORE
#define CONFIG_USER_BUSYBOX_MOUNT 1
#undef  CONFIG_USER_BUSYBOX_MOUNT_LOOP
#undef  CONFIG_USER_BUSYBOX_MTAB_SUPPORT
#undef  CONFIG_USER_BUSYBOX_NFSMOUNT
#undef  CONFIG_USER_BUSYBOX_MT
#undef  CONFIG_USER_BUSYBOX_MV
#undef  CONFIG_USER_BUSYBOX_NAMEIF
#undef  CONFIG_USER_BUSYBOX_NC
#undef  CONFIG_USER_BUSYBOX_NETSTAT
#define CONFIG_USER_BUSYBOX_NSLOOKUP 1
#undef  CONFIG_USER_BUSYBOX_OD
#undef  CONFIG_USER_BUSYBOX_OPENVT
#define CONFIG_USER_BUSYBOX_PASSWD 1
#undef  CONFIG_USER_BUSYBOX_PATCH
#define CONFIG_USER_BUSYBOX_PIDOF 1
#undef  CONFIG_USER_BUSYBOX_PING
#undef  CONFIG_USER_BUSYBOX_PING6
#undef  CONFIG_USER_BUSYBOX_PIPE_PROGRESS
#undef  CONFIG_USER_BUSYBOX_PIVOT_ROOT
#define CONFIG_USER_BUSYBOX_POWEROFF 1
#undef  CONFIG_USER_BUSYBOX_PRINTF
#undef  CONFIG_USER_BUSYBOX_PS
#undef  CONFIG_USER_BUSYBOX_PWD
#undef  CONFIG_USER_BUSYBOX_RDATE
#undef  CONFIG_USER_BUSYBOX_REALPATH
#undef  CONFIG_USER_BUSYBOX_READLINK
#undef  CONFIG_USER_BUSYBOX_REBOOT
#undef  CONFIG_USER_BUSYBOX_RENICE
#undef  CONFIG_USER_BUSYBOX_RESET
#undef  CONFIG_USER_BUSYBOX_RM
#undef  CONFIG_USER_BUSYBOX_RMDIR
#undef  CONFIG_USER_BUSYBOX_ROUTE
#undef  CONFIG_USER_BUSYBOX_RPM2CPIO
#undef  CONFIG_USER_BUSYBOX_RUN_PARTS
#undef  CONFIG_USER_BUSYBOX_RX
#undef  CONFIG_USER_BUSYBOX_SED
#undef  CONFIG_USER_BUSYBOX_SEQ
#undef  CONFIG_USER_BUSYBOX_SETKEYCODES
#define CONFIG_USER_BUSYBOX_SHELL 1
#undef  CONFIG_USER_BUSYBOX_ASH
#undef  CONFIG_USER_BUSYBOX_SH_IS_ASH
#undef  CONFIG_USER_BUSYBOX_HUSH
#undef  CONFIG_USER_BUSYBOX_SH_IS_HUSH
#undef  CONFIG_USER_BUSYBOX_LASH
#undef  CONFIG_USER_BUSYBOX_SH_IS_LASH
#define CONFIG_USER_BUSYBOX_MSH 1
#define CONFIG_USER_BUSYBOX_SH_IS_MSH 1
#define CONFIG_USER_BUSYBOX_COMMAND_EDITING 1
#define CONFIG_USER_BUSYBOX_COMMAND_SAVEHISTORY 1
#define CONFIG_USER_BUSYBOX_FEATURE_COMMAND_HISTORY (15)
#define CONFIG_USER_BUSYBOX_COMMAND_TAB_COMPLETION 1
#define CONFIG_USER_BUSYBOX_COMMAND_USERNAME_COMPLETION 1
#undef  CONFIG_USER_BUSYBOX_FEATURE_SH_EXTRA_QUIET
#define CONFIG_USER_BUSYBOX_TAB_COMPLETION 1
#define CONFIG_USER_BUSYBOX_USERNAME_COMPLETION 1
#undef  CONFIG_USER_BUSYBOX_SH_STANDALONE_SHELL
#define CONFIG_USER_BUSYBOX_SH_FANCY_PROMPT 1
#define CONFIG_USER_BUSYBOX_SH_EXTRA_QUIET 1
#undef  CONFIG_USER_BUSYBOX_SHA1SUM
#define CONFIG_USER_BUSYBOX_SLEEP 1
#undef  CONFIG_USER_BUSYBOX_FANCY_SLEEP
#undef  CONFIG_USER_BUSYBOX_SORT
#undef  CONFIG_USER_BUSYBOX_START_STOP_DAEMON
#undef  CONFIG_USER_BUSYBOX_STRINGS
#undef  CONFIG_USER_BUSYBOX_STTY
#undef  CONFIG_USER_BUSYBOX_SU
#undef  CONFIG_USER_BUSYBOX_SULOGIN
#undef  CONFIG_USER_BUSYBOX_SWAPONOFF
#undef  CONFIG_USER_BUSYBOX_SYNC
#undef  CONFIG_USER_BUSYBOX_SYSCTL
#define CONFIG_USER_BUSYBOX_SYSLOGD 1
#define CONFIG_USER_BUSYBOX_ROTATE_LOGFILE 1
#undef  CONFIG_USER_BUSYBOX_REMOTE_LOG
#undef  CONFIG_USER_BUSYBOX_IPC_SYSLOG
#undef  CONFIG_USER_BUSYBOX_TAIL
#undef  CONFIG_USER_BUSYBOX_TAR
#undef  CONFIG_USER_BUSYBOX_TEE
#undef  CONFIG_USER_BUSYBOX_TELNET
#define CONFIG_USER_BUSYBOX_TELNETD 1
#define CONFIG_USER_BUSYBOX_TELNETD_INETD 1
#define CONFIG_USER_BUSYBOX_TEST 1
#undef  CONFIG_USER_BUSYBOX_TEST_64
#undef  CONFIG_USER_BUSYBOX_TFTP
#define CONFIG_USER_BUSYBOX_TIME 1
#undef  CONFIG_USER_BUSYBOX_TOP
#undef  CONFIG_USER_BUSYBOX_TOUCH
#undef  CONFIG_USER_BUSYBOX_TR
#undef  CONFIG_USER_BUSYBOX_TRACEROUTE
#undef  CONFIG_USER_BUSYBOX_TRUE_FALSE
#undef  CONFIG_USER_BUSYBOX_TTY
#define CONFIG_USER_BUSYBOX_UDHCPC 1
#undef  CONFIG_USER_BUSYBOX_UDHCPD
#undef  CONFIG_USER_BUSYBOX_UDHCP_DEBUG
#undef  CONFIG_USER_BUSYBOX_UDHCP_SYSLOG
#define CONFIG_USER_BUSYBOX_UMOUNT 1
#define CONFIG_USER_BUSYBOX_MOUNT_FORCE 1
#define CONFIG_USER_BUSYBOX_UNAME 1
#undef  CONFIG_USER_BUSYBOX_UNCOMPRESS
#undef  CONFIG_USER_BUSYBOX_UNIQ
#define CONFIG_USER_BUSYBOX_UNIX2DOS 1
#undef  CONFIG_USER_BUSYBOX_UPDATE
#undef  CONFIG_USER_BUSYBOX_UPTIME
#undef  CONFIG_USER_BUSYBOX_USLEEP
#undef  CONFIG_USER_BUSYBOX_UUDECODE
#undef  CONFIG_USER_BUSYBOX_UUENCODE
#undef  CONFIG_USER_BUSYBOX_UNZIP
#undef  CONFIG_USER_BUSYBOX_VCONFIG
#define CONFIG_USER_BUSYBOX_VI 1
#define CONFIG_USER_BUSYBOX_VI_COLON 1
#define CONFIG_USER_BUSYBOX_VI_YANKMARK 1
#define CONFIG_USER_BUSYBOX_VI_SEARCH 1
#undef  CONFIG_USER_BUSYBOX_VI_USE_SIGNALS
#undef  CONFIG_USER_BUSYBOX_VI_DOT_CMD
#undef  CONFIG_USER_BUSYBOX_VI_READONLY
#undef  CONFIG_USER_BUSYBOX_VI_SETOPTS
#undef  CONFIG_USER_BUSYBOX_VI_SET
#define CONFIG_USER_BUSYBOX_VI_WIN_RESIZE 1
#undef  CONFIG_USER_BUSYBOX_VI_OPTIMIZE_CURSOR
#undef  CONFIG_USER_BUSYBOX_VLOCK
#undef  CONFIG_USER_BUSYBOX_WATCHDOGD
#undef  CONFIG_USER_BUSYBOX_WC
#undef  CONFIG_USER_BUSYBOX_WGET
#define CONFIG_USER_BUSYBOX_WHICH 1
#define CONFIG_USER_BUSYBOX_WHOAMI 1
#undef  CONFIG_USER_BUSYBOX_XARGS
#undef  CONFIG_USER_BUSYBOX_YES
#undef  CONFIG_USER_BUSYBOX_ZIP

/*
 * other features
 */
#undef  CONFIG_USER_BUSYBOX_BUFFERS_GO_ON_STACK
#undef  CONFIG_USER_BUSYBOX_BUFFERS_GO_IN_BSS
#undef  CONFIG_USER_BUSYBOX_USE_DEVPS_PATCH
#undef  CONFIG_USER_BUSYBOX_VERBOSE_USAGE
#define CONFIG_USER_BUSYBOX_AUTOWIDTH 1
#undef  CONFIG_USER_BUSYBOX_EXTRA_QUIET
#undef  CONFIG_USER_BUSYBOX_MINIX2
#undef  CONFIG_USER_BUSYBOX_SHADOWPASSWDS
#undef  CONFIG_USER_BUSYBOX_USE_BB_PWD_GRP
#undef  CONFIG_USER_BUSYBOX_DMALLOC
#undef  CONFIG_USER_BUSYBOX_EFENCE
#undef  CONFIG_USER_BUSYBOX_BUFFERS_USE_MALLOC
#undef  CONFIG_USER_BUSYBOX_DEVFS
#undef  CONFIG_USER_BUSYBOX_DEVPTS
#undef  CONFIG_USER_BUSYBOX_SUID
#undef  CONFIG_USER_BUSYBOX_LFS
#undef  CONFIG_USER_BUSYBOX_SELINUX
#undef  CONFIG_USER_BUSYBOX_STATIC
#undef  CONFIG_USER_BUSYBOX_IPV6
#undef  CONFIG_USER_BUSYBOX_CLEAN_UP
#undef  CONFIG_USER_BUSYBOX_HUMAN_READABLE
#undef  CONFIG_USER_BUSYBOX_LOCALE_SUPPORT

/*
 * Tinylogin
 */
#undef  CONFIG_USER_TINYLOGIN_TINYLOGIN

/*
 * MicroWindows
 */
#define CONFIG_USER_MICROWIN 1

/*
 * Compiling Options
 */
#define CONFIG_USER_MICROWIN_OPTIMIZE 1
#undef  CONFIG_USER_MICROWIN_DEBUG
#undef  CONFIG_USER_MICROWIN_VERBOSE

/*
 * Libraries
 */
#undef  CONFIG_USER_MICROWIN_MICROWIN
#define CONFIG_USER_MICROWIN_NANOX 1
#undef  CONFIG_USER_MICROWIN_SHAREDLIBS
#define CONFIG_USER_MICROWIN_NWIDGET 1
#undef  CONFIG_USER_MICROWIN_OBJFRAMEWORK

/*
 * Demos
 */
#undef  CONFIG_USER_MICROWIN_MICROWINDEMO
#define CONFIG_USER_MICROWIN_NANOXDEMO 1

/*
 * Applications
 */
#define CONFIG_USER_MICROWIN_NANOWM 1

/*
 * Settings
 */
#undef  CONFIG_USER_MICROWIN_MWPF_PALETTE
#undef  CONFIG_USER_MICROWIN_MWPF_TRUECOLOR0888
#undef  CONFIG_USER_MICROWIN_MWPF_TRUECOLOR888
#undef  CONFIG_USER_MICROWIN_MWPF_TRUECOLOR565
#define CONFIG_USER_MICROWIN_MWPF_TRUECOLOR555 1
#undef  CONFIG_USER_MICROWIN_MWPF_TRUECOLOR332
#undef  CONFIG_USER_MICROWIN_LINK_APP_INTO_SERVER
#define CONFIG_USER_MICROWIN_HAVE_FILEIO 1
#define CONFIG_USER_MICROWIN_HAVE_BMP_SUPPORT 1
#define CONFIG_USER_MICROWIN_HAVE_GIF_SUPPORT 1
#define CONFIG_USER_MICROWIN_HAVE_PNM_SUPPORT 1
#define CONFIG_USER_MICROWIN_HAVE_XPM_SUPPORT 1
#define CONFIG_USER_MICROWIN_HAVE_JPEG_SUPPORT 1
#define CONFIG_LIB_LIBJPEG 1
#define CONFIG_USER_MICROWIN_HAVE_PNG_SUPPORT 1
#define CONFIG_LIB_LIBPNG 1
#define CONFIG_LIB_ZLIB 1
#undef  CONFIG_USER_MICROWIN_HAVE_T1LIB_SUPPORT
#undef  CONFIG_USER_MICROWIN_HAVE_FREETYPE_SUPPORT
#define CONFIG_USER_MICROWIN_HAVE_SHAREDMEM_SUPPORT 1
#undef  CONFIG_USER_MICROWIN_HAVE_HZK_SUPPORT
#undef  CONFIG_USER_MICROWIN_HAVE_BIG5_SUPPORT
#undef  CONFIG_USER_MICROWIN_HAVE_GB2312_SUPPORT
#undef  CONFIG_USER_MICROWIN_HAVEMSFONTS
#undef  CONFIG_USER_MICROWIN_NOFONTSORCLIPPING
#define CONFIG_USER_MICROWIN_ERASEMOVE 1
#undef  CONFIG_USER_MICROWIN_UPDATEREGIONS
#undef  CONFIG_USER_MICROWIN_GRAYPALETTE

/*
 * Display Config
 */
#undef  CONFIG_USER_MICROWIN_X11
#define CONFIG_USER_MICROWIN_FRAMEBUFFER 1
#undef  CONFIG_USER_MICROWIN_FBVGA
#undef  CONFIG_USER_MICROWIN_VTSWITCH
#undef  CONFIG_USER_MICROWIN_PORTRAIT_MODE
#undef  CONFIG_USER_MICROWIN_FBREVERSE
#undef  CONFIG_USER_MICROWIN_VGALIB
#undef  CONFIG_USER_MICROWIN_HWVGA
#undef  CONFIG_USER_MICROWIN_CLEOVGA

/*
 * Mouse/Touch Screen
 */
#undef  CONFIG_USER_MICROWIN_GPMMOUSE
#undef  CONFIG_USER_MICROWIN_SERMOUSE
#undef  CONFIG_USER_MICROWIN_TPMOUSE
#undef  CONFIG_USER_MICROWIN_TPHELIO
#undef  CONFIG_USER_MICROWIN_ADSMOUSE
#undef  CONFIG_USER_MICROWIN_IPAQMOUSE
#undef  CONFIG_USER_MICROWIN_HARRIERMOUSE
#undef  CONFIG_USER_MICROWIN_PSIONMOUSE
#undef  CONFIG_USER_MICROWIN_UCTSMOUSE
#undef  CONFIG_USER_MICROWIN_DE2TSMOUSE
#undef  CONFIG_USER_MICROWIN_CLEOMOUSE
#undef  CONFIG_USER_MICROWIN_NOMOUSE
#define CONFIG_USER_MICROWIN_NDSMOUSE 1

/*
 * Keyboard
 */
#define CONFIG_USER_MICROWIN_TTYKBD 1
#undef  CONFIG_USER_MICROWIN_SCANKBD
#undef  CONFIG_USER_MICROWIN_PIPEKBD
#undef  CONFIG_USER_MICROWIN_CLEOKBD
#undef  CONFIG_USER_MICROWIN_NOKBD

/*
 * Install These Applications
 */
#define CONFIG_USER_MICROWIN_BIN_LANDMINE 1
#define CONFIG_USER_MICROWIN_BIN_LAUNCHER 1
#define CONFIG_USER_MICROWIN_BIN_MOVE 1
#undef  CONFIG_USER_MICROWIN_BIN_MTERM
#undef  CONFIG_USER_MICROWIN_BIN_MTEST
#undef  CONFIG_USER_MICROWIN_BIN_MTEST2
#undef  CONFIG_USER_MICROWIN_BIN_MUSERFD
#define CONFIG_USER_MICROWIN_BIN_NANO_X 1
#define CONFIG_USER_MICROWIN_BIN_NANOWM 1
#define CONFIG_USER_MICROWIN_BIN_NPANEL 1
#define CONFIG_USER_MICROWIN_BIN_NTERM 1
#undef  CONFIG_USER_MICROWIN_BIN_NTEST
#define CONFIG_USER_MICROWIN_BIN_NTETRIS 1
#define CONFIG_USER_MICROWIN_BIN_NXCLOCK 1
#define CONFIG_USER_MICROWIN_BIN_NXEV 1
#define CONFIG_USER_MICROWIN_BIN_NXKBD 1
#define CONFIG_USER_MICROWIN_BIN_NXLSCLIENTS 1
#define CONFIG_USER_MICROWIN_BIN_NXTERM 1
#define CONFIG_USER_MICROWIN_BIN_NXVIEW 1
#define CONFIG_USER_MICROWIN_BIN_SLIDER 1
#define CONFIG_USER_MICROWIN_BIN_VNC 1
#define CONFIG_USER_MICROWIN_BIN_WORLD 1

/*
 * Games
 */
#define CONFIG_USER_GAMES_ADVENT4 1
#define CONFIG_USER_GAMES_BSDGAMES 1
#define CONFIG_USER_GAMES_BSDGAMES_ADVENTURE 1
#define CONFIG_USER_GAMES_BSDGAMES_ARITHMETIC 1
#define CONFIG_USER_GAMES_BSDGAMES_BACKGAMMON 1
#define CONFIG_USER_GAMES_BSDGAMES_BATTLESTAR 1
#define CONFIG_USER_GAMES_BSDGAMES_BCD 1
#define CONFIG_USER_GAMES_BSDGAMES_BOGGLE 1
#define CONFIG_USER_GAMES_BSDGAMES_CAESAR 1
#define CONFIG_USER_GAMES_BSDGAMES_CANFIELD 1
#define CONFIG_USER_GAMES_BSDGAMES_CRIBBAGE 1
#define CONFIG_USER_GAMES_BSDGAMES_FISH 1
#define CONFIG_USER_GAMES_BSDGAMES_GOMOKU 1
#define CONFIG_USER_GAMES_BSDGAMES_HACK 1
#define CONFIG_USER_GAMES_BSDGAMES_HANGMAN 1
#define CONFIG_USER_GAMES_BSDGAMES_MILLE 1
#define CONFIG_USER_GAMES_BSDGAMES_MORSE 1
#define CONFIG_USER_GAMES_BSDGAMES_NUMBER 1
#define CONFIG_USER_GAMES_BSDGAMES_PIG 1
#define CONFIG_USER_GAMES_BSDGAMES_POM 1
#define CONFIG_USER_GAMES_BSDGAMES_PPT 1
#define CONFIG_USER_GAMES_BSDGAMES_PRIMES 1
#define CONFIG_USER_GAMES_BSDGAMES_QUIZ 1
#define CONFIG_USER_GAMES_BSDGAMES_RAIN 1
#define CONFIG_USER_GAMES_BSDGAMES_RANDOM 1
#define CONFIG_USER_GAMES_BSDGAMES_ROBOTS 1
#define CONFIG_USER_GAMES_BSDGAMES_SAIL 1
#define CONFIG_USER_GAMES_BSDGAMES_SNAKE 1
#define CONFIG_USER_GAMES_BSDGAMES_TETRIS 1
#define CONFIG_USER_GAMES_BSDGAMES_TREK 1
#define CONFIG_USER_GAMES_BSDGAMES_WORM 1
#define CONFIG_USER_GAMES_BSDGAMES_WORMS 1
#define CONFIG_USER_GAMES_BSDGAMES_WUMP 1
#define CONFIG_USER_GAMES_CNIBBLES 1
#define CONFIG_USER_GAMES_DUNGEON 1
#undef  CONFIG_USER_GAMES_NOIZ2SA
#define CONFIG_USER_GAMES_PACMAN 1
#undef  CONFIG_USER_GAMES_RUBIK
#define CONFIG_USER_GAMES_SUDOKU 1
#define CONFIG_USER_GAMES_XRICK 1
#define CONFIG_LIB_SDL 1
#define CONFIG_USER_GAMES_MELITE 1
#define CONFIG_LIB_SDL 1

/*
 * Miscellaneous Configuration
 */
#define CONFIG_USER_RAMIMAGE_NONE 1
#undef  CONFIG_USER_RAMIMAGE_RAMFS64
#undef  CONFIG_USER_RAMIMAGE_RAMFS128
#undef  CONFIG_USER_RAMIMAGE_RAMFS256
#undef  CONFIG_USER_RAMIMAGE_RAMFS512
#undef  CONFIG_USER_RAMIMAGE_RAMFS1024
#undef  CONFIG_USER_RAMIMAGE_RAMFS2048
#undef  CONFIG_USER_RAMIMAGE_RAMFS8192
#undef  CONFIG_USER_CGI_GENERIC
#undef  CONFIG_USER_CGIHTML
#undef  CONFIG_USER_DEMO_BUTTON
#undef  CONFIG_USER_DEMO_LATCH
#undef  CONFIG_USER_DEMO_MORSE
#undef  CONFIG_USER_DEMO_R2100

/*
 * Debug Builds
 */
#undef  CONFIG_LIB_DEBUG
#undef  CONFIG_USER_DEBUG

/*
 * Debug tools
 */
#undef  CONFIG_USER_TIMEPEG_TPT
#undef  CONFIG_USER_RTEST

/*
 * Debug libraries
 */
#undef  CONFIG_LIB_LIBCCMALLOC
#define CONFIG_VENDOR "Nintendo"
#define CONFIG_PRODUCT "DLDI"
#define CONFIG_LINUXDIR "linux-2.6.x"
#define CONFIG_LIBCDIR "uClibc"
#define CONFIG_LANGUAGE ""
#define VENDORS_AUTOCONF_INCLUDED
#undef AUTOCONF_INCLUDED
